backend:
  name: git-gateway
  repo: trafflab/traffacademy-gatsby-netlify-cms
  branch: webinar
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Страницы"
    files:
      - file: src/pages/index.md
        name: index
        label: 'Главная'
        fields:
          - {
            name: opening,
            label: opening,
            widget: object,
            fields:
              [
                { label: "Тэг", name: "tag", widget: "string" },
                { label: "Время", name: "time", widget: "string" },
                {
                  label: "title",
                  name: "title",
                  widget: "list",
                  allow_add: false,
                  fields:
                    [
                      { label: "part", name: "part", widget: "string" }
                    ]
                },
                { label: "Имя", name: "name", widget: "string" },
                { label: "jobTitle", name: "jobTitle", widget: "string" },
                { label: "buttonText", name: "buttonText", widget: "string" },
                { label: "buttonText_480", name: "buttonText_480", widget: "string" },
                { label: "giftText", name: "giftText", widget: "string" },
                { label: "giftText_480", name: "giftText_480", widget: "string" },
                { label: "imageAlt", name: "imageAlt", widget: "string" },
                {
                  label: "cards",
                  name: "cards",
                  widget: "list",
                  allow_add: false,
                  fields:
                    [
                      { label: "Title", name: "title", widget: "string" },
                      { label: "text", name: "text", widget: "string" }
                    ]
                },
              ]
          }
          - {
            name: whatIsIt,
            label: whatIsIt,
            widget: object,
            fields:
              [
                { label: "text", name: "text", widget: "string" },
                {
                  label: "title",
                  name: "title",
                  widget: "list",
                  allow_add: false,
                  fields:
                    [
                      { label: "part", name: "part", widget: "string" }
                    ]
                },
                {
                  label: "cards",
                  name: "cards",
                  widget: "list",
                  allow_add: false,
                  fields:
                    [
                      { label: "text", name: "text", widget: "string" }
                    ]

                },
              ]
          }
          - {
            name: itIsForYou,
            label: itIsForYou,
            widget: object,
            fields:
              [
                {
                  label: "title",
                  name: "title",
                  widget: "list",
                  allow_add: false,
                  fields:
                    [
                      { label: "part", name: "part", widget: "string" }
                    ]
                },
                { label: "buttonText", name: "buttonText", widget: "string" },
                {
                  label: "cards",
                  name: "cards",
                  widget: "list",
                  summary: '{{fields.text}}',
                  allow_add: false,
                  fields:
                    [
                      { label: "imageAlt", name: "imageAlt", widget: "string" },
                      { label: "text", name: "text", widget: "string" }
                    ]

                },
              ]
          }
          - {
            name: importantThings,
            label: importantThings,
            widget: object,
            fields:
              [
                {
                  label: "title",
                  name: "title",
                  widget: "list",
                  allow_add: false,
                  fields:
                    [
                      { label: "part", name: "part", widget: "string" }
                    ]
                },
                {
                  label: "cards",
                  name: "cards",
                  widget: "list",
                  summary: '{{fields.text}}',
                  allow_add: false,
                  fields:
                    [
                      { label: "imageAlt", name: "imageAlt", widget: "string" },
                      { label: "text", name: "text", widget: "string" }
                    ]

                },
              ]
          }
          - {
            name: perfectChoice,
            label: perfectChoice,
            widget: object,
            fields:
              [
                {
                  label: "title",
                  name: "title",
                  widget: "list",
                  allow_add: false,
                  fields:
                    [
                      { label: "part", name: "part", widget: "string" }
                    ]
                },
                {
                  label: "cards",
                  name: "cards",
                  widget: "list",
                  summary: '{{fields.title}}',
                  allow_add: false,
                  fields:
                    [
                      { label: "imageAlt", name: "imageAlt", widget: "string" },
                      { label: "title", name: "title", widget: "string" },
                      {
                        label: 'list',
                        name: 'list',
                        widget: "list",
                        allow_add: false,
                        fields: 
                          [
                            { label: "elementText", name: "elementText", widget: "string" },
                          ]
                      }
                    ]

                },
              ]
          }
          - {
            name: aboutUs,
            label: aboutUs,
            widget: object,
            fields:
              [
                {
                  label: "title",
                  name: "title",
                  widget: "list",
                  allow_add: false,
                  fields:
                    [
                      { label: "part", name: "part", widget: "string" }
                    ]
                },
                { label: "name", name: "name", widget: "string" },
                { label: "masterOf", name: "masterOf", widget: "string" },

              ]
          }
          - {
            name: partersMarquee,
            label: partersMarquee,
            widget: object,
            fields:
              [
                { label: "title", name: "title", widget: "string" },
              ]
          }
          - {
            name: participate,
            label: participate,
            widget: object,
            fields:
              [
                { label: "title", name: "title", widget: "string" },
                { label: "subtitle", name: "subtitle", widget: "string" },
                { label: "text", name: "text", widget: "string" },
                { label: "buttonText", name: "buttonText", widget: "string" },
              ]
          }
